name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Registry
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # 替换为你的用户名
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # 替换为你的密码
      run: echo "${DOCKER_PASSWORD}" | docker login harbor.bsszxc.com.cn -u "${DOCKER_USERNAME}" --password-stdin

    - name: Get Git commit ID
      id: git_commit_id
      run: echo "commit_id=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag harbor.bsszxc.com.cn/ops/kubernetes-event-exporter:$(date +%Y%m%d)-${{ steps.git_commit_id.outputs.commit_id }}

    - name: Push Docker image
      run: docker push harbor.bsszxc.com.cn/ops/kubernetes-event-exporter:$(date +%Y%m%d)-${{ steps.git_commit_id.outputs.commit_id }}
